apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: automation-apps
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: automation
  project: default
  source:
    repoURL: 'git@github.com:sarahdoi/dans.git'
    targetRevision: HEAD
    path: apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true